### ISSUE TITLE
Big problem......

### ISSUE THREAD

**Issue by Mac33299** [Froomeeth/Emiluras-Discovery#2]
Scion unable to spawn...
![Screenshot (4179)](https://user-images.githubusercontent.com/110599229/227967890-162faeb0-3d9b-489a-99c5-caf2da977b8d.png)

**Comment by Froomeeth** [comment]
Scion cannot spawn since the game treats serilia as if it was erekir and scion counts as a serpulo unit, being unable to spawn, im working on a Java ver so this wont happen again
